language: python
python:
  - "3.6"
before_install:
  - cd auction
install:
  - pip3 install -r requirements.txt
  - psql -c '\x' -c "CREATE ROLE django WITH SUPERUSER PASSWORD 'django' LOGIN;"
  - psql -c '\x' -c "CREATE DATABASE db_kurs OWNER django;"
before_script:
  - python3 manage.py makemigrations
  - python3 manage.py migrate
script:
  - python3 manage.py test tests/unit_tests  > test_log.log
  - python3 manage.py test tests/integration_tests > test_log.log
  - python3 manage.py test tests/e2e_tests > test_log.log
services:
  - postgresql