language: python
python:
  - "3.6"
before_install:
  - cd auction
install:
  - pip3 install -r requirements.txt
  - psql -c '\x' -c "CREATE ROLE django WITH SUPERUSER PASSWORD 'django' LOGIN;"
  - psql -c '\x' -c "CREATE DATABASE db_kurs OWNER django;"
before_script:
  - python3 manage.py makemigrations
  - python3 manage.py migrate
script:
  - python3 manage.py test tests/unit_tests > out.txt 2> err_unit.txt
  - python3 manage.py test tests/integration_tests > out.txt 2> err_integration.txt
  - python3 manage.py test tests/e2e_tests > out.txt 2> err_e2e.txt
services:
  - postgresql
deploy:
  provider: releases
  api_key: 951dfde7cdf71041c6c568b7e2e57cb9e7df860a
  file:
      "err_unit.txt"
      "err_integration.txt" 
      "err_e2e.txt"
  skip_cleanup: true
  on:
    tags: false
    all_branches: true