language: python
python:
  - "3.6"
before_install:
  - cd auction
install:
  - pip3 install -r requirements.txt
  - psql -c '\x' -c "CREATE ROLE django WITH SUPERUSER PASSWORD 'django' LOGIN;"
  - psql -c '\x' -c "CREATE DATABASE db_kurs OWNER django;"
before_script:
  - python3 manage.py makemigrations
  - python3 manage.py migrate
script:
  - python3 manage.py test tests/unit_tests 
  - python3 manage.py test tests/integration_tests 
  - python3 manage.py test tests/e2e_tests 
services:
  - postgresql
env:
  ARTIFACTS_KEY=(AWS access key id)
  ARTIFACTS_SECRET=(AWS secret access key)
  ARTIFACTS_BUCKET=(S3 bucket name)
addons:
  artifacts: true